/**
 * @file mqtt_compiler.h
 * @brief Compiler-specific optimization macros
 *
 * This header provides portable macros for compiler hints that can improve
 * performance on critical code paths. These are hints only - the code will
 * work correctly without them, but may run faster when the compiler can
 * use this information.
 *
 * Note: MQTT_INLINE, MQTT_LIKELY, MQTT_UNLIKELY are defined in mqtt_config.h
 * which is generated by CMake. This header provides additional macros not
 * covered by config.h.
 */

#ifndef MQTT_COMPILER_H
#define MQTT_COMPILER_H

/* Branch prediction hints - provided by mqtt_config.h */
/* MQTT_LIKELY(x) / MQTT_UNLIKELY(x) - use these from mqtt_config.h */

/* ========================================================================== */
/* Function attributes                                                        */
/* ========================================================================== */

/**
 * @brief Mark a function as a hot code path
 *
 * The compiler may optimize this function more aggressively and place it
 * in a hot section of the binary for better cache locality.
 */
#if defined(__GNUC__) || defined(__clang__)
#define MQTT_HOT __attribute__((hot))
#else
#define MQTT_HOT
#endif

/**
 * @brief Mark a function as a cold code path (error handling, etc.)
 *
 * The compiler may optimize for size rather than speed and place the
 * function away from hot code to improve cache performance.
 */
#if defined(__GNUC__) || defined(__clang__)
#define MQTT_COLD __attribute__((cold))
#else
#define MQTT_COLD
#endif

/**
 * @brief Mark a function as pure (depends only on arguments, no side effects)
 *
 * Allows the compiler to eliminate redundant calls with the same arguments.
 */
#if defined(__GNUC__) || defined(__clang__)
#define MQTT_PURE __attribute__((pure))
#else
#define MQTT_PURE
#endif

/**
 * @brief Mark a function as const (stricter than pure - no pointer derefs)
 *
 * Even more aggressive optimization than MQTT_PURE.
 */
#if defined(__GNUC__) || defined(__clang__)
#define MQTT_CONST __attribute__((const))
#else
#define MQTT_CONST
#endif

/* MQTT_INLINE is defined in mqtt_config.h */

/**
 * @brief Prevent function inlining
 */
#if defined(__GNUC__) || defined(__clang__)
#define MQTT_NOINLINE __attribute__((noinline))
#elif defined(_MSC_VER)
#define MQTT_NOINLINE __declspec(noinline)
#else
#define MQTT_NOINLINE
#endif

/* ========================================================================== */
/* Memory access hints                                                        */
/* ========================================================================== */

/**
 * @brief Prefetch data for reading
 *
 * Use sparingly - incorrect use can hurt performance more than help.
 */
#if defined(__GNUC__) || defined(__clang__)
#define MQTT_PREFETCH_READ(addr)  __builtin_prefetch((addr), 0, 3)
#define MQTT_PREFETCH_WRITE(addr) __builtin_prefetch((addr), 1, 3)
#else
#define MQTT_PREFETCH_READ(addr)  ((void)0)
#define MQTT_PREFETCH_WRITE(addr) ((void)0)
#endif

/**
 * @brief Mark a pointer as restrict (no aliasing)
 *
 * Allows the compiler to optimize memory accesses more aggressively.
 */
#if defined(__GNUC__) || defined(__clang__) || (defined(_MSC_VER) && _MSC_VER >= 1400)
#define MQTT_RESTRICT __restrict
#else
#define MQTT_RESTRICT
#endif

/* ========================================================================== */
/* Alignment hints                                                            */
/* ========================================================================== */

/**
 * @brief Specify alignment for a type or variable
 */
#if defined(__GNUC__) || defined(__clang__)
#define MQTT_ALIGNED(n) __attribute__((aligned(n)))
#elif defined(_MSC_VER)
#define MQTT_ALIGNED(n) __declspec(align(n))
#else
#define MQTT_ALIGNED(n)
#endif

/* ========================================================================== */
/* Unreachable code hint                                                      */
/* ========================================================================== */

/**
 * @brief Mark code as unreachable
 *
 * Tells the compiler this point should never be reached, allowing it to
 * optimize better and potentially catch bugs.
 */
#if defined(__GNUC__) || defined(__clang__)
#define MQTT_UNREACHABLE() __builtin_unreachable()
#elif defined(_MSC_VER)
#define MQTT_UNREACHABLE() __assume(0)
#else
#define MQTT_UNREACHABLE() ((void)0)
#endif

#endif /* MQTT_COMPILER_H */
